# Generated by Django 5.2.7 on 2025-10-30 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_vehicleowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.vehicleowner')),
            ],
        ),
    ]
