# Generated by Django 5.2.7 on 2025-11-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_trafficviolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficviolation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='violation_images/'),
        ),
    ]
